# Indian Express

In [103]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

service = Service('chromedriver.exe')

options = Options()
options.add_argument('--headless=new')

driver = webdriver.Chrome(service=service, options=options)
driver.get('https://indianexpress.com/latest-news/?ref=latestnews')

articles = driver.find_elements(by=By.CLASS_NAME, value='articles')

Headline = []
Summary = []
Source = []
for article in articles:
    Headline.append(article.find_element(by=By.CLASS_NAME, value='title').text)
    Summary.append(article.find_element(by=By.TAG_NAME, value='p',).text)
    Source.append('The Indian Express')

indian_express = pd.DataFrame({"Source":Source, "Headline":Headline, "Summary":Summary})
driver.close()

In [104]:
indian_express.head()

,Source,Headline,Summary
0,The Indian Express,Pahalgam Terror Attack Live Updates: UNSC memb...,Pahalgam Terror Attack Live Updates: The MHA o...
1,The Indian Express,Supreme Court sets aside Kerala High Court ver...,"Earlier, the Kerala High Court declared A Raja..."
2,The Indian Express,MP Board Supplementary Exams: MPBSE introduces...,"MPBSE MP Board Class 10th, 12th Supplementary ..."
3,The Indian Express,Delhi HC stays interim injunction against PS-2...,The earlier order had held that A R Rahman’s c...
4,The Indian Express,"MPBSE MP Board 10th 12th Result 2025, Mpbse.mp...","Mpbse.mponline.gov.in, MPBSE MP Board 10th, 12..."

# NBC News

In [106]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

service = Service('chromedriver.exe')

options = Options()
options.add_argument('--headless=new')

driver = webdriver.Chrome(service=service, options=options)
driver.get('https://www.nbcnews.com/')

headlines = driver.find_elements(by=By.CLASS_NAME, value='headline-large')
summaries = driver.find_elements(by=By.CSS_SELECTOR, value='.multi-story__dek.publico-txt.f3.lh-copy.fw4')

Headline = []
Summary = []
Source = []
for headline, summary in zip(headlines, summaries):
    Headline.append(headline.text)
    Summary.append(summary.text)
    Source.append('NBC')

nbc = pd.DataFrame({"Source":Source, "Headline":Headline, "Summary":Summary})
driver.close()

In [107]:
nbc.head()

,Source,Headline,Summary
0,NBC,Trump's call to reopen Alcatraz as a prison co...,Federal corrections experts and historians say...
1,NBC,EXCLUSIVE\nFormer DHS official targeted by Tru...,A host of questions remain about how the presi...
2,NBC,Met Gala celebrates historic 'Superfine: Tailo...,"Zendaya, A$AP Rocky and Kim Kardashian were am..."
3,NBC,Chaos at Newark Airport began with air traffic...,"The Barstool Sports founder, who is Jewish, sa..."
4,NBC,Netanyahu vows 'powerful' operation as Israel ...,The White House didn't respond to multiple que...

# Times of India

In [109]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

service = Service('chromedriver.exe')

options = Options()
options.add_argument('--headless=new')

driver = webdriver.Chrome(service=service, options=options)
driver.get('https://timesofindia.indiatimes.com/briefs')

articles = driver.find_elements(by=By.CLASS_NAME, value='brief_box')

Headline = []
Summary = []
Source = []
for article in articles:
    Headline.append(article.find_element(by=By.TAG_NAME, value='h2').text)
    Summary.append(article.find_element(by=By.TAG_NAME, value='p').text)
    Source.append('Times of India')

times_of_india = pd.DataFrame({"Source":Source, "Headline":Headline, "Summary":Summary})
driver.close()

In [110]:
times_of_india.head()

,Source,Headline,Summary
0,Times of India,‘Sorry Karnataka’: Sonu Nigam apologises after...,Singer Sonu Nigam has publicly apologized to K...
1,Times of India,'We have our eyes on everyone': Inform us if P...,Rajasthan police have heightened surveillance ...
2,Times of India,Man caught transporting wife's body stuffed in...,"In Pune, a 28-year-old man was apprehended for..."
3,Times of India,Can Trump sanctions on Russia force Putin's hand?,"Russia's economy, initially boosted by wartime..."
4,Times of India,'How can you be a Hindu if you criticise Manus...,Jyotirmath Shankaracharya Swami Avimukteshwara...

# Aggregating all the news

In [112]:
aggregated_news = pd.concat([indian_express, nbc, times_of_india], ignore_index=True)

aggregated_news

,Source,Headline,Summary
0,The Indian Express,Pahalgam Terror Attack Live Updates: UNSC memb...,Pahalgam Terror Attack Live Updates: The MHA o...
1,The Indian Express,Supreme Court sets aside Kerala High Court ver...,"Earlier, the Kerala High Court declared A Raja..."
2,The Indian Express,MP Board Supplementary Exams: MPBSE introduces...,"MPBSE MP Board Class 10th, 12th Supplementary ..."
3,The Indian Express,Delhi HC stays interim injunction against PS-2...,The earlier order had held that A R Rahman’s c...
4,The Indian Express,"MPBSE MP Board 10th 12th Result 2025, Mpbse.mp...","Mpbse.mponline.gov.in, MPBSE MP Board 10th, 12..."
...,...,...,...
79,Times of India,"Mehbooba Mufti slams closure of tourist spots,...",Mehbooba Mufti has strongly criticized the gov...
80,Times of India,Pakistan test-fires missile amid escalating te...,Pakistan's military recently conducted success...
81,Times of India,Four held for nomadic woman’s ‘rape-murder’ in...,"In a shocking incident near Nishat, Srinagar, ..."
82,Times of India,"Poonch terror hideout busted, tiffin-box IEDs ...",Security forces in Jammu and Kashmir's Poonch ...
83,Times of India,Delhi airport’s closed runway to open today,Great news for air travelers as Delhi Airport'...